name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  # Setup job that installs ffmpeg once for all test jobs
  setup:
    runs-on: ubuntu-latest
    outputs:
      ffmpeg-cache-key: ${{ steps.ffmpeg-cache.outputs.cache-key }}
    steps:
      - name: Setup ffmpeg cache key
        id: ffmpeg-cache
        run: echo "cache-key=ffmpeg-cache-$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Cache ffmpeg
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: /tmp/ffmpeg-cache
          key: ${{ steps.ffmpeg-cache.outputs.cache-key }}
          
      - name: Install ffmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          mkdir -p /tmp/ffmpeg-cache
          echo "ffmpeg installed at $(date)" > /tmp/ffmpeg-cache/installed.txt

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      
      - name: Setup ffmpeg from cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/ffmpeg-cache
          key: ${{ needs.setup.outputs.ffmpeg-cache-key }}
      
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run tests with coverage
        run: uv run pytest --cov=pydub --cov-report=xml

      - name: Generate Coverage Report
        if: matrix.python-version == '3.12'
        run: |
          uv run pytest --cov=pydub --cov-report=term --cov-report=html
          echo "Coverage report generated in htmlcov/ directory"

  deploy:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-3.10-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-3.10-

      - name: Install uv
        run: pip install uv

      - name: Install build dependencies
        run: uv sync --extra dev

      - name: Build package
        run: uv run python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}