name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache APT archives to avoid downloads in each test job
      - name: Cache APT archives
        id: apt-cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/ci-cd.yml') }}
      
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      # Upload APT archives as an artifact to share with test jobs
      - name: Upload APT archives
        run: |
          # Copy APT archives to a location we have permission to access
          sudo mkdir -p /tmp/apt-archives
          sudo cp -r /var/cache/apt/archives/*.deb /tmp/apt-archives/ || true
          sudo chmod -R 777 /tmp/apt-archives
        
      - name: Upload APT archives artifact
        uses: actions/upload-artifact@v4
        with:
          name: apt-archives
          path: /tmp/apt-archives
          retention-days: 1

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download the APT archives artifact from the setup job
      - name: Download APT archives
        uses: actions/download-artifact@v4
        with:
          name: apt-archives
          path: /tmp/apt-archives
      
      - name: Install ffmpeg using cached packages
        run: |
          # Copy the downloaded deb files to apt's cache directory
          sudo mkdir -p /var/cache/apt/archives
          sudo cp -f /tmp/apt-archives/*.deb /var/cache/apt/archives/ || true
          
          # Install ffmpeg from the cached packages
          sudo apt-get install -y ffmpeg

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run tests with coverage
        run: uv run pytest --cov=pydub --cov-report=xml

      - name: Generate Coverage Report
        if: matrix.python-version == '3.12'
        run: |
          uv run pytest --cov=pydub --cov-report=term --cov-report=html
          echo "Coverage report generated in htmlcov/ directory"

  deploy:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.10-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.10-
            ${{ runner.os }}-pip-

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-3.10-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-3.10-

      - name: Install uv
        run: pip install uv

      - name: Install build dependencies
        run: uv sync --extra dev

      - name: Build package
        run: uv run python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}